// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackServerApp } from "../stack";
import "./globals.css";
import Provider from "./Provider";
import ClientOnly from "./ClientOnly"; // ← mount guard
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientOnly>
          {" "}
          {/* ← hydrates after mount */}
          <StackProvider app={stackServerApp}>
            <StackTheme>
              <Provider>
                {children}
                <Toaster/>
              </Provider>
            </StackTheme>
          </StackProvider>
        </ClientOnly>
      </body>
    </html>
  );
}
